version: '3.4'

services:
  imagesrestapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "40080:80"
      - "44443:443"

  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"

  

