version: '3.4'

services:
  imagesrestapi:
    image: ${DOCKER_REGISTRY-}imagesrestapi
    container_name: images.api
    build:
      context: .
      dockerfile: ImagesRestApi/Dockerfile
    depends_on:
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest 
    container_name: mssql